# Generated by Django 4.2.9 on 2024-02-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.ManyToManyField(to='members.address'),
        ),
    ]
