# Generated by Django 4.2.9 on 2024-02-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_account_address_account_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addresses',
        ),
        migrations.AddField(
            model_name='address',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='members.account'),
        ),
    ]
