# Generated by Django 4.2.9 on 2024-02-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(blank=True, upload_to='project_pictures'),
        ),
    ]
